data:
    data_dir:         ../data_events/data_pdmx_remi+_balanced_simplified
    train_split:      ../data_events/data_pdmx_remi+_balanced_simplified/splits_piano/train_split.pkl
    val_split:        ../data_events/data_pdmx_remi+_balanced_simplified/splits_piano/val_split.pkl
    test_split:       ../data_events/data_pdmx_remi+_balanced_simplified/splits_piano/val_split.pkl
    vocab_path:       ../data_events/data_pdmx_remi+_balanced_simplified/dictionary.pkl
    time_path:        ../data_events/data_pdmx_remi+_balanced_simplified/timeSig2pieces_piano.pkl
    density_path:     ../data_events/data_pdmx_remi+_balanced_simplified/density2pieces_piano.pkl
    max_bars:         16
    enc_seqlen:       128
    dec_seqlen:       1280
    batch_size:       48
    balanced_time:    False
    balanced_density: True

tokenizer:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128   # vae
    num_quantizers:   8     # vae
    codebook_size:    1024  # vae
    pretrained_tokenizer_path:  ckpt/enc_dec_12L-16_bars-seqlen_1280-rvq-pdmx-n8-s1024-d128-beta1-density/params/step_16000-RC_0.122-CM_0.036-model.pt
    rotation_trick:   True
    rvq_type:         SimVQ # FSQ

model:
    dec_n_layer:      12
    dec_n_head:       16
    dec_d_model:      1024
    dec_d_ff:         2048
    d_embed:          1024
    d_latent:         128   # vae
    pretrained_params_path:  null
    pretrained_optim_path:   null
    use_attr_cls:     False

training:
    device:           cuda:4
    ckpt_dir:         null
    trained_steps:    0
    max_epochs:       1000
    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_warmup_steps:  100  # 200
    lr_decay_steps:   15000  # 150000
    free_bit_lambda:  0.25
    ckpt_interval:    1000
    log_interval:     10
    val_interval:     50
    val_rounds:       2

generate:
    temperature:                1.2
    nucleus_p:                  0.98
    use_latent_sampling:        False
    latent_sampling_var:        0.0
    max_bars:                   16       # could be set to match the longest input piece during generation (inference)
    dec_seqlen:                 1280     # could be set to match the longest input piece during generation (inference)
    max_input_dec_seqlen:       1024     # should be set to equal to or less than `dec_seqlen` used during training