data:
    data_dir:         data
    train_split:      data/data_splits_tokens/all_train.pkl
    val_split:        data/data_splits_tokens/small_valid.pkl
    test_split:       data/data_splits_tokens/all_test.pkl
    density_path:     data/data_splits_tokens/density2pieces_train.pkl
    max_bars:         16
    num_quantizers:   16     # vae
    codebook_size:    2048   # vae
    batch_size:       64
    balanced_density: True

model:
    dec_n_layer:      12
    dec_n_head:       16
    dec_d_model:      1024
    dec_d_ff:         2048
    d_embed:          512
    use_bar_emb:      True
    pretrained_params_path:  null
    pretrained_optim_path:   null

training:
    device:           cuda:1
    ckpt_dir:         null
    trained_steps:    0
    max_epochs:       1000
    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_warmup_steps:  200
    lr_decay_steps:   150000
    ckpt_interval:    5000
    val_interval:     50

data_music:
    data_dir:         data
    test_split:       data/data_splits_events/all/all_test.pkl
    vocab_path:       data/dictionary.pkl
    max_bars:         16
    enc_seqlen:       128
    dec_seqlen:       1280

tokenizer:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128   # vae
    num_quantizers:   16    # vae
    codebook_size:    2048  # vae
    pretrained_tokenizer_path:  ckpt/best_tokenizer/model.pt
    rotation_trick:   True
    rvq_type:         SimVQ # FSQ

generate:
    temperature:                1.1
    nucleus_p:                  0.9
    top_k:                      30
    max_bars:                   16     
    num_quantizers:             16       # vae
    codebook_size:              2048     # vae
    dec_seqlen:                 1280     