data:
    data_dir:         ../data_events/data_pdmx_remi+
    train_split:      ../data_events/data_pdmx_remi+/splits_piano/train_split.pkl
    val_split:        ../data_events/data_pdmx_remi+/splits_piano/val_split.pkl
    test_split:       ../data_events/data_pdmx_remi+/splits_piano/val_split.pkl
    vocab_path:       ../data_events/data_pdmx_remi+/dictionary.pkl
    max_bars:         16
    enc_seqlen:       56  # 128
    dec_seqlen:       1280
    batch_size:       16

model:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128
    d_polyph_emb:     64
    d_rfreq_emb:      64
    cond_mode:        in-attn
    pretrained_params_path:  null
    pretrained_optim_path:   null
    use_attr_cls:     False

training:
    device:           cuda:1
    ckpt_dir:         ./ckpt/enc_dec_12L-16_bars-seqlen_1280-recons-pdmx
    trained_steps:    0
    max_epochs:       1000
    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_warmup_steps:  100  # 200
    lr_decay_steps:   15000  # 150000
    no_kl_steps:      500  # 10000
    kl_cycle_steps:   500  # 5000
    kl_max_beta:      1.0
    free_bit_lambda:  0.25
    constant_kl:      False
    ckpt_interval:    1000
    log_interval:     10
    val_interval:     50
    val_rounds:       3

generate:
    temperature:                1.2
    nucleus_p:                  0.9
    use_latent_sampling:        False
    latent_sampling_var:        0.0
    max_bars:                   16       # could be set to match the longest input piece during generation (inference)
    dec_seqlen:                 1280     # could be set to match the longest input piece during generation (inference)
    max_input_dec_seqlen:       1024     # should be set to equal to or less than `dec_seqlen` used during training