data:
    data_dir:         data
    train_split:      data/data_splits_events/all/all_train.pkl
    val_split:        data/data_splits_events/all/all_valid.pkl
    test_split:       data/data_splits_events/all/all_test.pkl
    vocab_path:       data/dictionary.pkl
    max_bars:         16
    enc_seqlen:       128

model:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128   # vae
    num_quantizers:   16    # vae
    codebook_size:    2048  # vae
    pretrained_params_path:  null
    pretrained_optim_path:   null
    rotation_trick:   True
    rvq_type:         SimVQ # FSQ

training:
    device:           cuda:1