data:
    data_dir:         data
    train_split:      data/data_splits_timeLast_repeatBeat_noVelocity_strict_noOverlap/all/all_train.pkl
    val_split:        data/data_splits_timeLast_repeatBeat_noVelocity_strict_noOverlap/all/small_valid.pkl
    test_split:       data/data_splits_timeLast_repeatBeat_noVelocity_strict_noOverlap/all/all_test.pkl
    vocab_path:       data/dictionary_strict_noVelocity.pkl
    density_path:     data/data_splits_timeLast_repeatBeat_noVelocity_strict_noOverlap/all/density2pieces_train.pkl
    max_bars:         16
    enc_seqlen:       128
    dec_seqlen:       1280
    batch_size:       24
    balanced_density: True
    do_augment:       True

model:
    enc_n_layer:      12
    enc_n_head:       8
    enc_d_model:      512
    enc_d_ff:         2048
    dec_n_layer:      12
    dec_n_head:       8
    dec_d_model:      512
    dec_d_ff:         2048
    d_embed:          512
    d_latent:         128
    num_quantizers:   16
    codebook_size:    2048
    pretrained_params_path:  null
    pretrained_optim_path:   null
    rotation_trick:   True
    rvq_type:         SimVQ # FSQ, RVQ

training:
    device:           cuda:0
    ckpt_dir:         null
    trained_steps:    0
    max_epochs:       1000
    max_lr:           1.0e-4
    min_lr:           5.0e-6
    lr_warmup_steps:  200
    lr_decay_steps:   150000
    ckpt_interval:    1000
    val_interval:     50
    beta:             1

generate:
    max_input_dec_seqlen:       1024